### PR TITLE
Fixed bug of not having :D at the end

### PR DESCRIPTION
**Pull request by nielshuman**
I found a bug and fixed it
:D

### CODE REVIEW

**Comment by sophuric** [comment]
the person says hello

•_• < hello

**Comment by sophuric** [comment]
the person REALLY says hello

•_• < HELLO!

**Comment by sophuric** [comment]
the person is angry

\  /
•-•

**Comment by nielshuman** [comment]
hello person!

**Comment by sophuric** [comment]
yes
the person has grown **e a r s**
<•_•>

**Pull request closed without merging**
